# Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_ELEVENLABS_AGENT_ID
ENV VITE_ELEVENLABS_AGENT_ID=$VITE_ELEVENLABS_AGENT_ID

ARG VITE_N8N_WEBHOOK_URL
ENV VITE_N8N_WEBHOOK_URL=$VITE_N8N_WEBHOOK_URL

ARG VITE_N8N_CONSULTATION_WEBHOOK_URL
ENV VITE_N8N_CONSULTATION_WEBHOOK_URL=$VITE_N8N_CONSULTATION_WEBHOOK_URL

ARG VITE_GA4_ID
ENV VITE_GA4_ID=$VITE_GA4_ID

ARG VITE_CLARITY_ID
ENV VITE_CLARITY_ID=$VITE_CLARITY_ID

ARG VITE_GEMINI_VOICE_WEBHOOK_URL
ENV VITE_GEMINI_VOICE_WEBHOOK_URL=$VITE_GEMINI_VOICE_WEBHOOK_URL

ARG VITE_GEMINI_LIVE_TOKEN_URL
ENV VITE_GEMINI_LIVE_TOKEN_URL=$VITE_GEMINI_LIVE_TOKEN_URL

# Portal admin /admin — Supabase del portafolio (anon key pública; seguridad por RLS)
ARG VITE_SUPABASE_URL
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL

ARG VITE_SUPABASE_ANON_KEY
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY

ARG VITE_ADMIN_EMAILS
ENV VITE_ADMIN_EMAILS=$VITE_ADMIN_EMAILS

RUN npm run build

# Stage 2: Serve with Caddy
FROM caddy:2-alpine

COPY --from=builder /app/dist /srv
COPY Caddyfile /etc/caddy/Caddyfile

EXPOSE 80
